### ISSUE TITLE
How do you not lock root of the chord in blade opt

### ISSUE THREAD

**Issue by TheMercer** [WISDEM/WEIS#364]
analysis.yaml

```            
chord:
                flag: True             # Flag to optimize the chord
                n_opt: 16               # Number of control points along blade span
                max_decrease: 0.3      # Minimum multiplicative gain on existing chord at the n_opt locations
                max_increase: 3.       # Maximum multiplicative gain on existing chord at the n_opt locations
                index_start: 2         # Lock the first two DVs from blade root
                index_end: 16           # All DVs close to blade tip are active
```
index_start: 2         # Lock the first two DVs from blade root 
^ this line, how do I stop it locking do I just remove it ?
