### ISSUE TITLE
Why is Blade stiffness GJ much lower then expected

### ISSUE THREAD

**Issue by TheMercer** [WISDEM/WEIS#386]
This is the analysis yaml used for IEA 15 MW and the GJ stiffness (Torsion stiffness) come out much much lower and when ran in SONATA also, is low. is there any reason for this or how to add constraints to help make it stiffer?

trying to scale to a similar diameter of IEA 15MW with a new min and rated speed. 

Also webs in IEA has rotation, offset_y_pa and start_nd_arc, end_nd_arc which is used by SONATA or both ? 

```
    blade:
        aero_shape:
            twist:
                flag: True             # Flag to optimize the twist
                inverse: False         # Flag to determine twist from the user-defined desired margin to stall (defined in constraints)
                n_opt: 8               # Number of control points along blade span
                max_decrease: 0.08722222222222221 # Maximum decrease for the twist in [rad] at the n_opt locations
                max_increase: 0.08722222222222221 # Maximum increase for the twist in [rad] at the n_opt locations
                index_start: 0         # Lock the first two DVs from blade root
                index_end: 8           # All DVs close to blade tip are active
            chord:
                flag: True             # Flag to optimize the chord
                n_opt: 8               # Number of control points along blade span
                max_decrease: 0.3      # Minimum multiplicative gain on existing chord at the n_opt locations
                max_increase: 3.       # Maximum multiplicative gain on existing chord at the n_opt locations
                index_start: 0         # Lock the first DV from blade root
                index_end: 8           # The last DV at blade tip is locked
            af_positions:
                flag: True
                af_start: 1
        structure:
            - layer_name: Spar_Cap_SS
              n_opt: 8               # Number of control points along blade span
              max_decrease: 0      # Maximum nondimensional decrease at the n_opt locations
              max_increase: 5      # Maximum nondimensional increase at the n_opt locations
              index_start: 0         # Lock the first DV from blade root
              index_end: 8           # The last DV at blade tip is locked
            - layer_name: Spar_Cap_PS
              n_opt: 8               # Number of control points along blade span
              max_decrease: 0      # Maximum nondimensional decrease at the n_opt locations
              max_increase: 5      # Maximum nondimensional increase at the n_opt locations
              index_start: 0         # Lock the first DV from blade root
              index_end: 8           # The last DV at blade tip is locked
            - layer_name: LE_reinforcement
              n_opt: 8               # Number of control points along blade span
              max_decrease: 0      # Maximum nondimensional decrease at the n_opt locations
              max_increase: 5.       # Maximum nondimensional increase at the n_opt locations
              index_start: 0         # Lock the first DV from blade root
              index_end: 8           # The last DV at blade tip is locked
            - layer_name: TE_reinforcement_SS
              n_opt: 8               # Number of control points along blade span
              max_decrease: 0      # Maximum nondimensional decrease at the n_opt locations
              max_increase: 5.       # Maximum nondimensional increase at the n_opt locations
              index_start: 0         # Lock the first DV from blade root
              index_end: 8           # The last DV at blade tip is locked
            - layer_name: TE_reinforcement_PS
              n_opt: 8               # Number of control points along blade span
              max_decrease: 0      # Maximum nondimensional decrease at the n_opt locations
              max_increase: 5.       # Maximum nondimensional increase at the n_opt locations
              index_start: 0         # Lock the first DV from blade root
              index_end: 8           # The last DV at blade tip is locked
            - layer_name: Shell_skin
              n_opt: 8               # Number of control points along blade span
              max_decrease: 0      # Maximum nondimensional decrease at the n_opt locations
              max_increase: 5.       # Maximum nondimensional increase at the n_opt locations
              index_start: 0         # Lock the first DV from blade root
              index_end: 8           # The last DV at blade tip is locked
            - layer_name: Shell_skin_inner
              n_opt: 8               # Number of control points along blade span
              max_decrease: 0      # Maximum nondimensional decrease at the n_opt locations
              max_increase: 5.       # Maximum nondimensional increase at the n_opt locations
              index_start: 0         # Lock the first DV from blade root
              index_end: 8           # The last DV at blade tip is locked
merit_figure: LCOE
    
constraints:
    blade:
        strains_spar_cap_ss:
            flag: True         # Flag to impose constraints on maximum strains (absolute value) in the spar cap on the blade suction side
            max:    3500.e-6   # Value of maximum strains [-]
            index_start: 1     # Do not enforce constraint at the first station from blade root of the n_opt from spar_cap_ss
            index_end: 8       # Do not enforce constraint at the last station at blade tip of the n_opt from spar_cap_ss
        strains_spar_cap_ps:
            flag: True         # Flag to impose constraints on maximum strains (absolute value) in the spar cap on the blade pressure side
            max:    3500.e-6   # Value of maximum strains [-]
            index_start: 1     # Do not enforce constraint at the first station from blade root of the n_opt from spar_cap_ps
            index_end: 8       # Do not enforce constraint at the last station at blade tip of the n_opt from spar_cap_ps
        strains_te_ss:
            flag: False        # Flag to impose constraints on maximum strains (absolute value) in the spar cap on the blade suction side
            max:    3500.e-6   # Value of maximum strains [-]
            index_start: 1     # Do not enforce constraint at the first station from blade root of the n_opt from spar_cap_ss
            index_end: 8       # Do not enforce constraint at the last station at blade tip of the n_opt from spar_cap_ss
        strains_te_ps:
            flag: False        # Flag to impose constraints on maximum strains (absolute value) in the spar cap on the blade pressure side
            max:    3500.e-6   # Value of maximum strains [-]
            index_start: 1     # Do not enforce constraint at the first station from blade root of the n_opt from spar_cap_ps
            index_end: 8       # Do not enforce constraint at the last station at blade tip of the n_opt from spar_cap_ps
        tip_deflection:
            flag: True
            margin: 1.4175
        stall:
            flag: True    # Constraint on minimum stall margin
            margin: 0.087 # Value of minimum stall margin in [rad]
        moment_coefficient:
            flag: True    # Constraint on minimum stall margin
            max: 0.16
```
